### ISSUE TITLE
Set up error;

### ISSUE THREAD

**Issue by RLN1961** [SudheerNotes/cams2csv#3]
Could not set up.

**Comment by SudheerNotes** [comment]
Hi - I have released a new version today (v1.01)...so can you please give it a try..?

**Comment by RLN1961** [comment]
I could get the ZIP file downloaded.  But still the problem of set up error is coming.  
[Set up failing.docx](https://github.com/SudheerNotes/cams2csv/files/12715796/Set.up.failing.docx)

**Comment by SudheerNotes** [comment]
Hi...don't worry, I understand and I'm not a Techie either this is just my passion.

Regarding your issue, I think your Antivirus must be blocking the exe file, lets try one more trick as suggested [here](https://installforge.net/forums/viewtopic.php?t=753)

**Steps:**
1. Uninstall previous installation 
2. And then download installation file and double click on the setup file
3. During the installation process in step two it will ask you for a Destination folder and the default path in your case was `C:\Program Files (x86)\Cams2CSV\` before you click on next...just delete "\" at the end

New path should look like this `C:\Program Files (x86)\Cams2CSV`
 
5. Click on next and finish the installation

Let me know if this has worked.

**Comment by SudheerNotes** [comment]
Since no response, I'm closing this issue
