### ISSUE TITLE
Wrong Fund Name

### ISSUE THREAD

**Issue by githubrakesh** [SudheerNotes/cams2csv#4]
Hi .. Noticed one bug while trying for my statement:
![Capture2](https://github.com/SudheerNotes/cams2csv/assets/12220956/541c1ee7-01a1-48d6-b57e-90bd0e0f7901)

The above records list the wrong fund name. 
There were no transactions on the Motilal Oswal S and P 500 Index Fund on those dates but for a scheme of Navi.

**Comment by SudheerNotes** [comment]
Hi, are you saying those units belongs to a different Fund..? if so, can you please copy paste exact fund name (just the fund name, no personal details please) from your CAMS PDF statement..? 

Its possible that REGEX may have failed to pick this up.

**Comment by githubrakesh** [comment]
Yes, they belong to Navi Nasdaq 100 FOF

**Comment by SudheerNotes** [comment]
Sorry for the delay - Thanks for highlighting, it was a bug in Fund Name Regx pattern and I have fixed it now for next release. 
So, I'll close this issue.
